### ISSUE TITLE
Theme structure

### ISSUE THREAD

**Issue by Wooody82** [GoogleChrome/ProgressiveWordPress#25]
Hi Surma,
Thanks for the theme. I just wonder if you could describe the theme structure as it's not as a normal theme.
And I see the style.css is empty? so how WordPress get the name of the theme?
And I see there is an error message here:

https://pwp.dassur.ma/wp-content/themes/surmblog/
Fatal error: Uncaught Error: Call to undefined function etag_start() in /var/www/html/wp-content/themes/surmblog/index.php:16 Stack trace: #0 {main} thrown in /var/www/html/wp-content/themes/surmblog/index.php on line 16

Thanks

**Comment by surma** [comment]
Why are you going to that URL? I don’t think the theme subfolder is supposed to be opened directly. Just go to https://pwp.dassur.ma to see the theme in action :D

The theme is a completely normal theme, just what you see in this repository is the _source code_. You have to build the theme with the instructions in the README.

`styles.css` is empty because I didn’t want to use the WordPress style loading functionality, which didn’t offer me enough control. So I am inlining all critical styles manually in [`header.php`](https://github.com/GoogleChromeLabs/ProgressiveWordPress/blob/master/src/theme/header.php#L39-L46) and lazy-loading the remaining styles a couple lines later.

HTH

**Comment by Wooody82** [comment]
Hi,
Yes I see, its nice and fast loaded.  I am just testing and checking the theme.
I see the theme in the dist/theme .. But I just wonder if I want to add all the code with git and use only dist/theme for the theme.
In your way I need to always do it locally and then move the dist/theme or rename it to be in theme-name.

And I see you used define( 'PWA_THEME_MANIFEST_ARG', 'jetpack_app_manifest' ); .. is that from Jetpack module? or is it the AMP module?

Thanks

**Comment by surma** [comment]
Do you expect to change the theme code? Otherwise you just build once and copy `dist/theme` (which is exactly what I do in the [`Dockerfile`](https://github.com/GoogleChromeLabs/ProgressiveWordPress/blob/master/Dockerfile#L28)).

> And I see you used define( 'PWA_THEME_MANIFEST_ARG', 'jetpack_app_manifest' ); .. is that from Jetpack module? or is it the AMP module?

That got contributed from the Jetpack team :)

**Comment by Wooody82** [comment]
Ok Thanks for that Surma, I dont know how Docker works and I dont want to use it :D
